export const FEATURES = [
  {
    title: 'Secure Auth',
    description: 'Built-in authentication system with role-based access.',
    category: ['Security', 'Authentication'],
    tools: ['Firebase', 'JWT'],
    rating: 5,
    image: '/images/auth.jpg',
    createdAt: '2024-07-01',
  },
  {
    title: 'Dark Mode',
    description: 'Automatic theme switch with user preference support.',
    category: ['UI', 'Accessibility'],
    tools: ['Tailwind', 'React Context'],
    rating: 4,
    image: '/images/darkmode.jpg',
    createdAt: '2024-06-28',
  },
  {
    title: 'Responsive Grid',
    description: 'Adaptive grid layouts for all screen sizes.',
    category: ['Layout', 'UI'],
    tools: ['Tailwind'],
    rating: 4.5,
    image: '/images/grid.jpg',
    createdAt: '2024-06-20',
  },
  {
    title: 'Analytics',
    description: 'Track user behavior and performance insights.',
    category: ['Insights', 'Data'],
    tools: ['Google Analytics', 'Mixpanel'],
    rating: 4,
    image: '/images/analytics.jpg',
    createdAt: '2024-06-18',
  },
  {
    title: 'Performance Boost',
    description: 'Optimize performance with lazy loading and caching.',
    category: ['Performance', 'UX'],
    tools: ['React Lazy', 'Service Worker'],
    rating: 5,
    image: '/images/performance.jpg',
    createdAt: '2024-06-15',
  },
  {
    title: 'Multi-language Support',
    description: 'Switch between multiple locales seamlessly.',
    category: ['Localization', 'Accessibility'],
    tools: ['i18next'],
    rating: 4.5,
    image: '/images/language.jpg',
    createdAt: '2024-06-12',
  },
  {
    title: 'Custom Themes',
    description: 'User-defined color schemes and typography.',
    category: ['UI'],
    tools: ['Tailwind'],
    rating: 3.5,
    image: '/images/themes.jpg',
    createdAt: '2024-06-10',
  },
  {
    title: 'Dev Tools Integration',
    description: 'Integrate with browser dev tools and APIs.',
    category: ['Developer', 'Integration'],
    tools: ['Chrome DevTools', 'REST APIs'],
    rating: 4.8,
    image: '/images/devtools.jpg',
    createdAt: '2024-06-08',
  },
  {
    title: 'Offline Support',
    description: 'Use the app without internet connection.',
    category: ['Performance'],
    tools: ['Service Worker'],
    rating: 4.7,
    image: '/images/offline.jpg',
    createdAt: '2024-06-06',
  },
  {
    title: 'Real-Time Updates',
    description: 'Live data push with WebSocket support.',
    category: ['Realtime', 'Communication'],
    tools: ['Socket.io', 'WebSocket'],
    rating: 5,
    image: '/images/realtime.jpg',
    createdAt: '2024-06-04',
  },
  {
    title: 'Notifications',
    description: 'Push, email, and toast notifications built-in.',
    category: ['Communication', 'UX'],
    tools: ['Toastify', 'Firebase'],
    rating: 4.3,
    image: '/images/notifications.jpg',
    createdAt: '2024-06-02',
  },
  {
    title: 'Drag & Drop',
    description: 'Move items with native drag and drop.',
    category: ['Interaction', 'UI'],
    tools: ['React DnD'],
    rating: 4.2,
    image: '/devtools.jpg',
    createdAt: '2024-05-30',
  },
  {
    title: 'Data Export',
    description: 'Export reports in CSV, PDF, or Excel format.',
    category: ['Data', 'Tools'],
    tools: ['xlsx', 'jsPDF'],
    rating: 4,
    image: '/images/export.jpg',
    createdAt: '2024-05-28',
  },
  {
    title: 'Advanced Search',
    description: 'Search across categories with fuzzy matching.',
    category: ['Data', 'UX'],
    tools: ['Fuse.js'],
    rating: 4.6,
    image: '/images/search.jpg',
    createdAt: '2024-05-25',
  },
  {
    title: 'Version Control',
    description: 'Track changes and rollback updates.',
    category: ['Developer', 'Workflow'],
    tools: ['Git', 'GitHub'],
    rating: 4.4,
    image: '/images/git.jpg',
    createdAt: '2024-05-22',
  },
  {
    title: 'AI Suggestions',
    description: 'Auto-generate content with GPT integration.',
    category: ['AI', 'Productivity'],
    tools: ['OpenAI', 'GPT-4'],
    rating: 5,
    image: '/images/ai.jpg',
    createdAt: '2024-05-20',
  },
  {
    title: 'Code Formatter',
    description: 'Prettify and lint your code with ease.',
    category: ['Developer', 'Tools'],
    tools: ['Prettier', 'ESLint'],
    rating: 4.1,
    image: '/images/format.jpg',
    createdAt: '2024-05-18',
  },
  {
    title: 'Two-Factor Auth',
    description: 'Add an extra layer of security.',
    category: ['Security'],
    tools: ['TOTP', 'Authy'],
    rating: 4.9,
    image: '/images/2fa.jpg',
    createdAt: '2024-05-15',
  },
  {
    title: 'Custom Dashboards',
    description: 'Design your own admin panels.',
    category: ['UI', 'Dashboard'],
    tools: ['React', 'Tailwind', 'Chart.js'],
    rating: 4.7,
    image: '/images/dashboard.jpg',
    createdAt: '2024-05-10',
  },
];